"""The `install` / `uninstall` commands: configure agent harness permissions."""

from __future__ import annotations

import json
from pathlib import Path

import click

_HARNESSES = ("claude-code", "codex")

# Commands that are safe to run without human review.
_ALLOWED_COMMANDS = ["query", "schema", "validate"]

# Both `dbastion` and `dbast` aliases.
_ALIASES = ["dbastion", "dbast"]

# --- Claude Code ---
# Uses permissions.allow / permissions.ask / permissions.deny
# Evaluation order: deny → ask → allow (first match wins).
# https://docs.anthropic.com/en/docs/claude-code/settings


def _claude_allow_rules() -> list[str]:
    """Rules for permissions.allow — auto-executed commands."""
    rules = []
    for cmd in _ALLOWED_COMMANDS:
        for alias in _ALIASES:
            rules.append(f"Bash({alias} {cmd} *)")
    return rules


def _claude_ask_rules() -> list[str]:
    """Rules for permissions.ask — always prompt the human."""
    rules = []
    for alias in _ALIASES:
        rules.append(f"Bash({alias} approve *)")
    return rules


def _merge_rules(existing: list[str], new: list[str]) -> tuple[list[str], int]:
    """Merge new rules into existing list, deduplicating. Returns (merged, added_count)."""
    added = 0
    merged = list(existing)
    for rule in new:
        if rule not in merged:
            merged.append(rule)
            added += 1
    return merged, added


def _remove_rules(existing: list[str], ours: set[str]) -> tuple[list[str], int]:
    """Remove exact dbastion-managed rules. Returns (filtered, removed_count)."""
    filtered = [r for r in existing if r not in ours]
    return filtered, len(existing) - len(filtered)


def _install_claude_code(project_dir: Path, *, global_: bool) -> None:
    settings_dir = Path.home() / ".claude" if global_ else project_dir / ".claude"
    settings_path = settings_dir / "settings.json"
    settings_dir.mkdir(parents=True, exist_ok=True)

    settings = json.loads(settings_path.read_text()) if settings_path.exists() else {}

    permissions = settings.setdefault("permissions", {})
    allow = permissions.get("allow", [])
    ask = permissions.get("ask", [])

    allow, allow_added = _merge_rules(allow, _claude_allow_rules())
    ask, ask_added = _merge_rules(ask, _claude_ask_rules())

    permissions["allow"] = allow
    permissions["ask"] = ask
    settings["permissions"] = permissions
    settings_path.write_text(json.dumps(settings, indent=2) + "\n")

    total = allow_added + ask_added
    if total:
        click.echo(f"  {settings_path}: added {allow_added} allow + {ask_added} ask rules")
    else:
        click.echo(f"  {settings_path}: already configured")


def _uninstall_claude_code(project_dir: Path, *, global_: bool) -> None:
    settings_dir = Path.home() / ".claude" if global_ else project_dir / ".claude"
    settings_path = settings_dir / "settings.json"

    if not settings_path.exists():
        click.echo(f"  {settings_path}: not found")
        return

    settings = json.loads(settings_path.read_text())
    permissions = settings.get("permissions", {})
    changed = False

    rule_sets = {"allow": set(_claude_allow_rules()), "ask": set(_claude_ask_rules())}
    for key in ("allow", "ask"):
        existing = permissions.get(key, [])
        filtered, removed = _remove_rules(existing, rule_sets[key])
        if removed:
            permissions[key] = filtered
            changed = True

    if changed:
        settings["permissions"] = permissions
        settings_path.write_text(json.dumps(settings, indent=2) + "\n")
        click.echo(f"  {settings_path}: removed dbastion rules")
    else:
        click.echo(f"  {settings_path}: no dbastion rules found")


# --- Codex ---
# Uses prefix_rule() in .rules files.
# Project: ./.codex/rules/
# User:    ~/.codex/rules/
# Confirmed against openai/codex implementation:
# project config layers are rooted at ./.codex, and exec policy loads
# <config_folder>/rules/*.rules.


def _codex_rules() -> str:
    """Generate Codex rules file content."""
    lines = ["# dbastion rules — auto-generated by `dbastion install codex`", ""]
    for cmd in _ALLOWED_COMMANDS:
        for alias in _ALIASES:
            lines.append('prefix_rule(')
            lines.append(f'    pattern = ["{alias}", "{cmd}"],')
            lines.append('    decision = "allow",')
            lines.append('    justification = "Governed by dbastion",')
            lines.append(')')
            lines.append("")

    for alias in _ALIASES:
        lines.append('prefix_rule(')
        lines.append(f'    pattern = ["{alias}", "approve"],')
        lines.append('    decision = "prompt",')
        lines.append('    justification = "Human approval required",')
        lines.append(')')
        lines.append("")

    return "\n".join(lines)


def _codex_rules_dir(project_dir: Path, *, global_: bool) -> Path:
    if global_:
        return Path.home() / ".codex" / "rules"
    return project_dir / ".codex" / "rules"


def _install_codex(project_dir: Path, *, global_: bool) -> None:
    rules_dir = _codex_rules_dir(project_dir, global_=global_)
    rules_path = rules_dir / "dbastion.rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    rules_content = _codex_rules()
    if rules_path.exists() and rules_path.read_text() == rules_content:
        click.echo(f"  {rules_path}: already up to date")
    else:
        rules_path.write_text(rules_content)
        click.echo(f"  {rules_path}: rules written")


def _uninstall_codex(project_dir: Path, *, global_: bool) -> None:
    rules_dir = _codex_rules_dir(project_dir, global_=global_)
    rules_path = rules_dir / "dbastion.rules"
    if rules_path.exists():
        rules_path.unlink()
        click.echo(f"  {rules_path}: removed")
    else:
        click.echo(f"  {rules_path}: not found")


# --- CLI commands ---

_INSTALLERS = {
    "claude-code": (_install_claude_code, _uninstall_claude_code),
    "codex": (_install_codex, _uninstall_codex),
}


@click.command()
@click.argument("harness", type=click.Choice(_HARNESSES))
@click.option("--global", "global_", is_flag=True, help="Install to user-level config.")
def install(harness: str, global_: bool) -> None:
    """Configure an agent harness for dbastion.

    Sets up permissions so the harness allows dbastion commands
    (query, schema, validate) and prompts on approve.

    \b
    Supported harnesses:
        claude-code    .claude/settings.json (permissions.allow + ask)
        codex          .codex/rules/dbastion.rules (prefix_rule)

    \b
    Examples:
        dbastion install claude-code          # project-level
        dbastion install codex --global       # user-level
    """
    project_dir = Path.cwd()
    installer, _ = _INSTALLERS[harness]

    scope = "global" if global_ else f"project ({project_dir})"
    click.echo(f"Installing dbastion for {harness} ({scope}):")
    installer(project_dir, global_=global_)
    click.echo("Done.")


@click.command()
@click.argument("harness", type=click.Choice(_HARNESSES))
@click.option("--global", "global_", is_flag=True, help="Uninstall from user-level config.")
def uninstall(harness: str, global_: bool) -> None:
    """Remove dbastion configuration from an agent harness.

    \b
    Examples:
        dbastion uninstall claude-code
        dbastion uninstall codex --global
    """
    project_dir = Path.cwd()
    _, uninstaller = _INSTALLERS[harness]

    scope = "global" if global_ else f"project ({project_dir})"
    click.echo(f"Uninstalling dbastion from {harness} ({scope}):")
    uninstaller(project_dir, global_=global_)
    click.echo("Done.")
